// List of random statements
const statements = [
    "Sometimes, the best ideas come when you’re doing absolutely nothing.",
    "The hardest part of a workout is starting.",
    "Nobody actually knows what they're doing most of the time.",
    "Sleep is the best thing in the world, but it’s also the most underrated.",
    "Sometimes it’s just easier to pretend you understand.",
    "The best conversations happen in the most unexpected places.",
    "Life doesn’t have a reset button, but sometimes you need one.",
    "The only thing better than a good song is a great playlist.",
    "We all secretly wish we could have a pet dinosaur.",
    "If you can’t find the remote, it’s probably under the couch.",
    "People always say time flies, but no one tells you how fast a day can drag.",
    "It’s hard to be in a bad mood when you’re surrounded by pizza.",
    "Every good story starts with ‘I was just minding my own business…’",
    "We all have a secret obsession with mystery shows.",
    "You can never have enough snacks during a movie marathon.",
    "Some days you just need to stay in your pajamas all day.",
    "There’s no such thing as too much chocolate.",
    "Everyone has that one song that never gets old.",
    "No one tells you how great it feels to find a perfect meme.",
    "The best part about a rainy day is staying inside and doing absolutely nothing.",
    "You know it’s a good day when you find money in your pocket.",
    "Procrastination is like a credit card: it’s a lot of fun until you get the bill.",
    "You can't always control the situation, but you can control your reaction.",
    "It’s the little things that make life extraordinary.",
    "Not every day needs to be productive. Some days are for just being.",
    "A nap is never a waste of time.",
    "There’s something magical about the first bite of pizza.",
    "People who can quote movies word for word have a special kind of power.",
    "Some of the best moments in life happen when you least expect them.",
    "There’s no better feeling than finishing a really good book.",
    "If you can make someone laugh, you’re doing something right.",
    "No one tells you how difficult it is to fold a fitted sheet.",
    "Sometimes you just need a change of scenery to change your mood.",
    "The best advice is usually the simplest one.",
    "It’s not about how many friends you have, it’s about the ones that matter.",
    "Coffee is a gift from the universe.",
    "The perfect playlist can make any moment better.",
    "The first bite of food is always the best one.",
    "There’s a certain freedom in not caring what people think of you.",
    "Having a good sense of humor makes everything easier.",
    "There’s nothing quite like a midnight snack.",
    "No matter how old you are, playing in the rain never gets old.",
    "You don’t need to have everything figured out to enjoy life.",
    "A perfect day includes good food, good friends, and no responsibilities.",
    "Sometimes, all you need is a good laugh to brighten your day.",
    "The secret to happiness is not taking things too seriously.",
    "Everyone has their own unique way of doing things, and that’s okay.",
    "Sometimes, the best way to solve a problem is to step away for a moment.",
    "You can never go wrong with a solid pair of sneakers.",
    "Life is all about finding balance between work and play.",
    "It’s the imperfections that make life beautiful.",
    "There’s no better feeling than the satisfaction of finishing a project.",
    "Laughter is the best stress relief.",
    "Some days, the best thing you can do is just breathe and take it easy.",
    "The best days are the ones where nothing goes as planned but everything still turns out great.",
    "The world would be a better place if everyone learned how to laugh at themselves.",
    "The most memorable moments often happen by accident.",
    "Sometimes you just have to dance like no one’s watching.",
    "Being kind doesn’t cost anything, but it’s worth everything.",
    "You can’t please everyone, and that’s perfectly okay.",
    "The best way to learn something is by doing it, not just reading about it.",
    "Sometimes the smallest gestures have the biggest impact.",
    "There’s always room for one more slice of pizza.",
    "A good night’s sleep can fix almost anything.",
    "A day without music is like a day without sunshine.",
    "Everyone has a talent, sometimes you just need to discover it.",
    "Sometimes you need to be a little selfish to take care of yourself.",
    "The best adventures happen when you least expect them.",
    "There’s no such thing as too much laughter.",
    "The best memories are made with friends, not things.",
    "Nothing beats the feeling of finishing a book you couldn’t put down.",
    "The best advice comes from the people who’ve lived through it all.",
    "It's impossible to be in a bad mood when there’s a puppy around.",
    "The hardest part of a workout is getting started, but it’s always worth it.",
    "Life’s too short to worry about what other people think.",
    "Sometimes the simplest things bring the most joy.",
    "There’s no greater feeling than being in the middle of a good conversation.",
    "A cup of hot chocolate fixes everything.",
    "The world feels a little bit better when you're surrounded by friends.",
    "You never forget the first time you heard your favorite song.",
    "Not every problem needs to be solved; sometimes you just need to sit with it.",
    "Spending time with good people is the best kind of therapy.",
    "The best way to cheer yourself up is to cheer someone else up.",
    "There’s something magical about the first snow of the year.",
    "A little kindness goes a long way.",
    "The best things in life aren’t things.",
    "Even on bad days, there’s always something to be grateful for.",
    "The best part of being a teenager is not having to pretend to be an adult yet.",
    "Nothing beats the feeling of getting cozy with a good book.",
    "There’s no such thing as too much chocolate or coffee.",
    "It’s the small victories that add up to the big wins.",
    "You’ll never regret a day spent with good friends.",
    "Sometimes you just need to take a break and relax.",
    "A good laugh can fix a lot of problems.",
    "You can't beat a good pizza on a Friday night.",
    "The best memories are often the ones that weren’t planned.",
    "We all have a secret love for cheesy pop songs.",
    "A new season always brings new opportunities.",
    "The world would be a better place if people smiled more.",
    "It’s the little things that can make the biggest difference.",
    "Music has a way of making everything better.",
    "No matter how old you get, there’s always room for a good ice cream sundae.",
    "Some days, the best thing you can do is laugh it off.",
    "Even the most ordinary day can turn into something special.",
    "You never forget your first concert.",
    "No one can ever have too many good memories.",
    "Sometimes, you just need a day to be lazy.",
    "The best memories come from the least expected moments.",
    "Life is way too short to spend it worrying about things you can’t control.",
    "The greatest gift you can give someone is your time.",
    "There’s nothing like the feeling of being home after a long trip.",
    "Music can change your mood in seconds.",
    "Sometimes it’s okay to not have everything figured out.",
    "The best days are the ones that make you forget about time.",
    "There’s something magical about the smell of fresh rain.",
    "Nothing beats the feeling of having a good conversation with a friend.",
    "A little adventure goes a long way in making memories.",
    "Sometimes the best way to relax is to just do nothing at all.",
    "There’s no better way to end the day than with a good movie.",
    "You can’t go wrong with a cheesy slice of pizza.",
    "Good vibes only—life’s too short for anything else.",
    "Some days, the best thing you can do is take a deep breath and smile.",
    "The best memories are made during the most random moments.",
    "Good friends make everything better.",
    "The best kind of day is one that surprises you in a good way.",
    "Some days are meant to be slow and easy.",
    "The best part about weekends is no alarms.",
    "Life is more fun when you stop worrying about what people think.",
    "The best conversations happen over food.",
    "Nothing beats the feeling of crossing something off your to-do list.",
    "Sometimes all you need is a change of scenery.",
    "Good food and great company make the perfect combo.",
    "The best days are the ones with no plans at all.",
    "A good mood can be contagious.",
    "The right playlist can make any moment feel special.",
    "Sometimes it’s okay to not have everything figured out right now.",
    "The best part of a day is the evening when everything slows down.",
    "Life gets a little easier when you learn to let go of the small stuff.",
    "Some of the best days are unplanned, spontaneous ones.",
    "A good book is the perfect escape from reality.",
    "There’s nothing better than the feeling of finishing something you’ve worked hard on.",
    "Some moments are worth remembering, even if they seem insignificant at the time.",
    "The best adventures are the ones that happen when you least expect them.",
    "Sometimes, the simplest things in life are the best.",
    "The best part about a rainy day is staying inside with a warm drink.",
    "Every day is an opportunity to make a new memory.",
    "The best moments happen when you’re just living in the present.",
    "The best way to end a day is with a good movie or show.",
    "Life doesn’t need to be perfect to be great."
    "English is easy to learn.",
    "Money is more important than love.",
    "Students should be required to study English in elementary school.",
    "Violence is sometimes necessary.",
    "Personality is more important than beauty.",
    "People who live in apartments shouldn't own pets.",
    "No job is perfect.",
    "Everyone is good at something.",
    "We are not alone in the universe.",
    "Life was better 20 years ago.",
    "The most important thing about a job is the salary.",
    "You can know a lot about a person from the clothes he or she wears.",
    "Teachers should be able to use physical punishment.",
    "Global warming isn't real.",
    "There are actions we can take to stop global warming.",
    "There are no such things as ghosts.",
    "Everyone has the right to have an opinion even if the opinion is false according to well-known facts.",
    "People get offended too easily nowadays.",
    "What goes around comes around. (If you do good, good will come to you / If you do bad, bad things will happen to you.)",
    "Parents should never hit their children.",
    "Table manners and etiquette have become less important in the 21st century.",
    "Smoking marijuana should be legal.",
    "Police officers should not carry guns.",
    "Criminals who take a life (kill someone) should spend their entire life behind bars.",
    "Graffiti is art, not crime.",
    "Prisoners are sent to jail to be reeducated.",
    "Men should open doors for women.",
    "Men and women can never really be equal.",
    "Women are better at teaching children than men are.",
    "Men are smarter than women.",
    "Companies should have quotas on their executive boards to make them 50% female.",
    "At a bar, men should initiate conversation with women (and not the other way around).",
    "People who get plastic surgery usually look worse later in life.",
    "Nowadays, people are too dependent on medicine.",
    "This country's healthcare system needs a lot of improvement.",
    "If you feel unwell, you should go to the doctor.",
    "Western medicine is more effective than Eastern medicine.",
    "People who use acupuncture are crazy.",
    "People should be more concerned about their health.",
    "Beauty products, vitamins, and mineral supplements generally provide the benefits they promise.",
    "Home remedies can be just as useful as medicine from a pharmacy.",
    "Obesity is a disease.",
    "Humans shouldn't drink the milk of other animals such as cows.",
    "There should be an extra tax on unhealthy food.",
    "Worrying about cancer can give you cancer.",
    "Life would be better without government or rules.",
    "People should be able to criticize the government.",
    "The government has the right to monitor phone calls and e-mails.",
    "The government should increase environmental regulations on businesses.",
    "Women should be allowed to wear a niqab (or face veil) to civic ceremonies.",
    "We should tax the rich to help the poor.",
    "New Canadians who become terrorists should lose their citizenship and be sent back to where they came from.",
    "The government should be stricter on immigration.",
    "Canada should not participate in the war against ISIS.",
    "Voting for a political party that is unlikely to win the election is wasting your vote."
];

// Function to get a random statement
function getRandomStatement() {
    const randomIndex = Math.floor(Math.random() * statements.length);
    return statements[randomIndex];
}

// Function to update the displayed statement
function updateStatement() {
    const statementElement = document.getElementById('statement');
    statementElement.textContent = getRandomStatement();
}

// Event listeners for the buttons
document.getElementById('agreeBtn').addEventListener('click', function() {
    alert("You agreed!"); // Handle the response
    updateStatement(); // Update the statement
});

document.getElementById('disagreeBtn').addEventListener('click', function() {
    alert("You disagreed!"); // Handle the response
    updateStatement(); // Update the statement
});

// Initialize the first random statement
updateStatement();
